build improvements
Signed-off-by: Swapnanil Gupta <swpnlg@amazon.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -77,6 +77,11 @@ jobs:
           
           cd ../../
           python3 bin/lima-and-qemu.py
+          if [ $? -ne 0 ]; then
+            echo "Failed to create lima-and-qemu archive"
+            exit 1
+          fi
+          
           mv src/lima/lima-and-qemu.tar.gz src/lima/lima-and-qemu.macos-aarch64.tar.gz
         shell: zsh {0}
 
@@ -161,6 +166,11 @@ jobs:
           
           cd ../../
           python3 bin/lima-and-qemu.py
+          if [ $? -ne 0 ]; then
+            echo "Failed to create lima-and-qemu archive"
+            exit 1
+          fi
+
           mv src/lima/lima-and-qemu.tar.gz src/lima/lima-and-qemu.macos-x86_64.tar.gz
         shell: zsh {0}
 
